"use client"
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar"
import { useRouter, usePathname } from "next/navigation";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const router = useRouter()
  const path = usePathname()

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} h-[100vh] w-[100vw] antialiased backdrop-blu backdrop-brightness-50`}>
        
        {/* <Navbar /> */}

        {/* <div className={`text-center h-[10vh] bg-black`}>
          
          <div className={`hidden sm:flex text-white justify-between mx-5`}>
            <div className="basis-1/3"></div>
            <div className="basis-1/3 justify-between my-5 text-sm">
              <p className={`cursor-pointer ${path=="/" ? `font-bold text-yellow-500` : ``}`} onClick={()=>router.push('/')}>Home</p>
            </div>
            <div className="basis-1/3"></div>            
          </div>

        </div> */}

        <div className="sm:h-[86vh]">
          {children}
        </div>

      </body>
    </html>
  );
}
